---
- name: 'Include OS-specific variables'
  include_vars: "{{ ansible_os_family }}.yml"

- name: 'Define vncserver packages'
  set_fact:
    vncserver_packages: "{{ __vncserver_packages | list }}"
  when: vncserver_packages is not defined

- include: "install-{{ ansible_os_family }}.yml"

- include: "configure-{{ ansible_os_family }}.yml"
